# -*- coding: utf-8 -*-
"""Manifest for the OmniSync module."""
{
    "name": "OmniSync",
    "summary": "Universal synchronization and integration engine for Odoo Enterprise",
    "version": "18.0.6.0.0",
    "category": "Technical/Tools",
    "author": "OmniSync Team",
    "website": "https://www.example.com",
    "license": "OPL-1",
    "depends": [
        "base",
        "queue_job",
        "web",
        "mail",
    ],
    "data": [
        "security/omnisync_security.xml",
        "security/ir.model.access.csv",
        "data/omnisync_data.xml",
        "data/omnisync_template_data.xml",
        "data/omnisync_cron.xml",
        "views/omnisync_menus.xml",
        "views/omnisync_auth_views.xml",
        "views/omnisync_system_views.xml",
        "views/omnisync_flow_views.xml",
        "views/omnisync_mapping_views.xml",
        "views/omnisync_job_views.xml",
        "views/omnisync_dashboard_views.xml",
        "views/omnisync_conflict_views.xml",
        "views/omnisync_version_views.xml",
        "views/omnisync_template_views.xml",
        "views/omnisync_wizard_views.xml",
        "views/omnisync_templates.xml",
        "views/omnisync_binding_views.xml",
        "views/omnisync_validation_views.xml",
        "views/omnisync_policy_views.xml",
        "views/omnisync_health_views.xml",
        "views/omnisync_runbook_views.xml",
    ],
    "application": True,
    "installable": True,
}
